### ISSUE TITLE
CircuitPython firmware download stats broken

### ISSUE THREAD

**Issue by tekktrik** [adafruit/circuitpython-org#1136]
[The download stats page for the CircuitPython firmware](https://circuitpython.org/stats) appears to be broken.  Not sure what's causing the empty tables, but I'll look into it.

**Comment by makermelissa** [comment]
Not sure if it's related to #1135, but the json is valid.

**Comment by tekktrik** [comment]
It looks like the releases have empty lists for the `asset` key and so aren't building anything but the header: https://github.com/adafruit/circuitpython-org/blob/0400b3cc84a786baf233cd181ef2a2a9c3435018/assets/javascript/stats.js#L16-L25

**Comment by dhalbert** [comment]
No, we haven't uploaded assets to GitHub for years. The download stats we use for sorting which boards are most popular  are generated by me, using AWS Athena, every time we do a release. That goes into the `download` counts in the board json.

If you want me to do other queries that update periodically I could, but it would be work to do this dynamically. Generating the download counts for all the boards takes about 15 seconds (and maybe costs about 15 cents). Maybe we should just get rid of this page. The downloads per board could be reported somewhere, if we care, since we already have that.

**Comment by makermelissa** [comment]
I think updating the page to dynamically read the boards.json file via JavaScript should be possible and likely not too difficult. Automatically regenerating as static page via adabot or some similar mechanism doesn't seem practical since there would be a new PR every day that somebody would need to merge. I think the nature of this issue is as the title states the page is broken and it should just be redone if it's useful for people. I imagine something like this shouldn't take more than a couple of hours, if that.

**Comment by makermelissa** [comment]
Oof, I just realized it was by CP version and not by board like I was thinking when I just wrote that. I think removing this altogether actually page makes more sense. I think as Dan stated, it costs money and time to generate and I doubt it that's useful for most people. I seems more like a fun fact.

**Comment by tekktrik** [comment]
Want me to handle the PR to remove it?
